[project]
name = "repl-nix-cryptoinsightsdashboard"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "plotly>=5.24.1",
    "streamlit>=1.40.1",
    "textblob>=0.18.0.post0",
    "wordcloud>=1.9.4",
    "groq",
    "yfinance",
]
